# Generated by Django 3.2.9 on 2021-11-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admisssion_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mothers_name', models.CharField(max_length=50)),
                ('grade_value', models.FloatField(max_length=3)),
                ('review', models.TextField(max_length=500)),
            ],
        ),
    ]
