# Generated by Django 3.2.9 on 2021-11-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admisssion_Student',
            new_name='Admission_Student',
        ),
    ]
